### ISSUE TITLE
Doesn't show banner with error TimeoutException

### ISSUE THREAD

**Issue by ngoxuanhien** [ratson/cordova-plugin-admob-free#159]
Hello, I'm trying to show banner ads but it fails with errors:
`E/Ads: Error waiting for future.
                                                                            java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException
                                                                                at com.google.android.gms.internal.zzalf.get(Unknown Source)
                                                                                at com.google.android.gms.internal.zzakl.zza(Unknown Source)
                                                                                at com.google.android.gms.internal.zzacb.zza(Unknown Source)
                                                                                at com.google.android.gms.internal.zzacb.zzb(Unknown Source)
                                                                                at com.google.android.gms.internal.zzacd.run(Unknown Source)
                                                                                at com.google.android.gms.internal.zzahj.call(Unknown Source)
                                                                                at com.google.android.gms.internal.zzahk.run(Unknown Source)`

My code here 
`    const bannerConfig: AdMobFreeBannerConfig = {
      id: ADMOB_ID
    };

    this.admobFree.banner.config(bannerConfig);

    this.admobFree.banner.prepare()
      .then(() => {
      if(this.isNotFullLicense){
        this.admobFree.banner.show();
      }else {
        this.admobFree.banner.remove();
      }
      })
      .catch(e => console.log(e));`

I working on some device but on android 7.0 or latest the ads not showing. Any ideas ?

**Comment by SArsalanK** [comment]
Similar problem! :(

> 10-10 15:47:21.430 29883-30587/? E/Ads: Error waiting for future.
    java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException
        at com.google.android.gms.ads.internal.util.future.af.get(:com.google.android.gms@14366007@14.3.66 (020304-213742215):18)
        at com.google.android.gms.ads.internal.util.future.g.a(:com.google.android.gms@14366007@14.3.66 (020304-213742215):11)
        at com.google.android.gms.ads.internal.request.service.c.a(:com.google.android.gms@14366007@14.3.66 (020304-213742215):36)
        at com.google.android.gms.ads.internal.request.service.c.a(:com.google.android.gms@14366007@14.3.66 (020304-213742215):169)
        at com.google.android.gms.ads.internal.request.service.f.run(:com.google.android.gms@14366007@14.3.66 (020304-213742215):1)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.util.concurrent.TimeoutException
        at com.google.android.gms.ads.internal.util.future.m.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:818) 
10-10 15:47:22.280 13964-13979/com.ashleytobeybuttons.whosyourdaddyboy I/Ads: No fill from ad server.
10-10 15:47:22.300 13964-13964/com.ashleytobeybuttons.whosyourdaddyboy W/Ads: Failed to load ad: 3
