### ISSUE TITLE
couldn't add plugin

### ISSUE THREAD

**Issue by le93us** [ratson/cordova-plugin-admob-free#165]
Hello;

`debian 9.3`, `node 9`, `npm 5.6`

when I execute command
```sh
cordova plugin add cordova-plugin-admob-free --save
```

I get next error
```sh
(node:28519) UnhandledPromiseRejectionWarning: CordovaError: Failed to fetch plugin cordova-plugin-admob-free@^0.13.0 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 254 Error output:
npm WARN lab_application@1.1.1 No repository field.
npm WARN lab_application@1.1.1 No license field.

npm ERR! path /home/lex/Desktop/lab/dev_app/node_modules/cordova-android/node_modules/abbrev
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/home/lex/Desktop/lab/dev_app/node_modules/cordova-android/node_modules/abbrev' -> '/home/lex/Desktop/lab/dev_app/node_modules/cordova-android/node_modules/.abbrev.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-02-12T09_20_59_946Z-debug.log
    at /usr/local/share/.config/yarn/global/node_modules/cordova-lib/src/plugman/fetch.js:173:37
    at _rejected (/usr/local/share/.config/yarn/global/node_modules/cordova-fetch/node_modules/q/q.js:864:24)
    at /usr/local/share/.config/yarn/global/node_modules/cordova-fetch/node_modules/q/q.js:890:30
    at Promise.when (/usr/local/share/.config/yarn/global/node_modules/cordova-fetch/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/usr/local/share/.config/yarn/global/node_modules/cordova-fetch/node_modules/q/q.js:808:41)
    at /usr/local/share/.config/yarn/global/node_modules/cordova-fetch/node_modules/q/q.js:624:44
    at runSingle (/usr/local/share/.config/yarn/global/node_modules/cordova-fetch/node_modules/q/q.js:137:13)
    at flush (/usr/local/share/.config/yarn/global/node_modules/cordova-fetch/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:150:11)
(node:28519) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:28519) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Can someone help to fix it?

**Comment by hermann77** [comment]
What is the solution? I have the same problem.
