### ISSUE TITLE
Can't build app

### ISSUE THREAD

**Issue by piernik** [ratson/cordova-plugin-admob-free#207]
I can't build app. I'm using ionic as main framework.
How I installed it?
`npm install --save @ionic-native/admob-free`  v 4.7.0
`ionic cordova plugin add cordova-plugin-admob-free`  v 0.15.0
`ionic cordova platform remove android`
`ionic cordova platform add android --save`
`ionic cordova run android`

That error was returned:

```
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDesugarForDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: Error while executing java process with main class com.google.devtools.build.android.desugar.Desugar with arguments {--input C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\19.jar --output C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\desugar\debug\21.jar --input C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\21.jar --output C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\desugar\debug\23.jar --input C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\9.jar --output C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\desugar\debug\11.jar --input C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\16.jar --output C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\desugar\debug\18.jar --input C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\0.jar --output C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\desugar\debug\2.jar --input C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\22.jar --output C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\desugar\debug\24.jar --input C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\1.jar --output C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\desugar\debug\3.jar --input C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\12.jar --output C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\desugar\debug\14.jar --input C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\3.jar --output C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\desugar\debug\5.jar --classpath_entry C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\CordovaLib\build\intermediates\intermediate-jars\debug\classes.jar --classpath_entry C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\classes\debug --classpath_entry C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\0.jar --classpath_entry C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\1.jar --classpath_entry C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\2.jar --classpath_entry C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\3.jar --classpath_entry C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\4.jar --classpath_entry C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\5.jar --classpath_entry C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\6.jar --classpath_entry C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\7.jar --classpath_entry C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\8.jar --classpath_entry C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\9.jar --classpath_entry C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\10.jar --classpath_entry C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\11.jar --classpath_entry C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\12.jar --classpath_entry C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\13.jar --classpath_entry C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\14.jar --classpath_entry C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\15.jar --classpath_entry C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\16.jar --classpath_entry C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\17.jar --classpath_entry C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\18.jar --classpath_entry C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\19.jar --classpath_entry C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\20.jar --classpath_entry C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\21.jar --classpath_entry C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\22.jar --classpath_entry C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\23.jar --bootclasspath_entry c:\Users\Lukasz\AppData\Local\Android\android-sdk\platforms\android-26\android.jar --bootclasspath_entry c:\Users\Lukasz\AppData\Local\Android\android-sdk\platforms\android-26\optional\org.apache.http.legacy.jar --bootclasspath_entry C:\Program Files\Java\jdk1.8.0_40\jre\lib\resources.jar --bootclasspath_entry C:\Program Files\Java\jdk1.8.0_40\jre\lib\rt.jar --bootclasspath_entry C:\Program Files\Java\jdk1.8.0_40\jre\lib\jsse.jar --bootclasspath_entry C:\Program Files\Java\jdk1.8.0_40\jre\lib\jce.jar --bootclasspath_entry C:\Program Files\Java\jdk1.8.0_40\jre\lib\charsets.jar --bootclasspath_entry C:\Program Files\Java\jdk1.8.0_40\jre\lib\jfr.jar --min_sdk_version 19 --nodesugar_try_with_resources_if_needed --desugar_try_with_resources_omit_runtime_classes}

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 43s
40 actionable tasks: 40 executed
(node:23060) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: cmd: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
C:\Users\Lukasz\.gradle\caches\transforms-1\files-1.1\play-services-maps-15.0.0.aar\606493ec5d60a18f8a4bd38f9f55f221\jars\classes.jar(com/google/android/gms/maps/MapsInitializer.class): warning: Cannot find annotation method 'value()' in type 'GuardedBy': class file for javax.annotation.concurrent.GuardedBy not found
C:\Users\Lukasz\.gradle\caches\transforms-1\files-1.1\play-services-base-15.0.0.aar\eace685f37b82bd7d9e223f22f440695\jars\classes.jar(com/google/android/gms/common/api/GoogleApiClient.class): warning: Cannot find annotation method 'value()' in type 'GuardedBy'
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 warnings
Exception in thread "main" java.lang.IllegalArgumentException
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:108)
	at com.google.devtools.build.android.desugar.DefaultMethodClassFixer$DefaultMethodFinder.visit(DefaultMethodClassFixer.java:471)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at com.google.devtools.build.android.desugar.DefaultMethodClassFixer.defaultMethodsDefined(DefaultMethodClassFixer.java:319)
	at com.google.devtools.build.android.desugar.DefaultMethodClassFixer.visitEnd(DefaultMethodClassFixer.java:88)
	at org.objectweb.asm.ClassVisitor.visitEnd(Unknown Source)
	at com.google.devtools.build.android.desugar.InterfaceDesugaring.visitEnd(InterfaceDesugaring.java:85)
	at org.objectweb.asm.ClassVisitor.visitEnd(Unknown Source)
	at com.google.devtools.build.android.desugar.LambdaDesugaring.visitEnd(LambdaDesugaring.java:150)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at com.google.devtools.build.android.desugar.Desugar.desugarClassesInInput(Desugar.java:401)
	at com.google.devtools.build.android.desugar.Desugar.desugarOneInput(Desugar.java:326)
	at com.google.devtools.build.android.desugar.Desugar.desugar(Desugar.java:280)
	at com.google.devtools.build.android.desugar.Desugar.main(Desugar.java:584)

Exception in thread "main" java.lang.IllegalArgumentException
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:108)
	at com.google.devtools.build.android.desugar.DefaultMethodClassFixer$DefaultMethodFinder.visit(DefaultMethodClassFixer.java:471)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at com.google.devtools.build.android.desugar.DefaultMethodClassFixer.defaultMethodsDefined(DefaultMethodClassFixer.java:319)
	at com.google.devtools.build.android.desugar.DefaultMethodClassFixer.visitEnd(DefaultMethodClassFixer.java:88)
	at org.objectweb.asm.ClassVisitor.visitEnd(Unknown Source)
	at com.google.devtools.build.android.desugar.InterfaceDesugaring.visitEnd(InterfaceDesugaring.java:85)
	at org.objectweb.asm.ClassVisitor.visitEnd(Unknown Source)
	at com.google.devtools.build.android.desugar.LambdaDesugaring.visitEnd(LambdaDesugaring.java:150)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at com.google.devtools.build.android.desugar.Desugar.desugarClassesInInput(Desugar.java:401)
	at com.google.devtools.build.android.desugar.Desugar.desugarOneInput(Desugar.java:326)
	at com.google.devtools.build.android.desugar.Desugar.desugar(Desugar.java:280)
	at com.google.devtools.build.android.desugar.Desugar.main(Desugar.java:584)


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDesugarForDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: Error while executing java process with main class com.google.devtools.build.android.desugar.Desugar with arguments {--input C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\19.jar --output C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\desugar\debug\21.jar --input C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\21.jar --output C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\desugar\debug\23.jar --input C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\9.jar --output C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\desugar\debug\11.jar --input C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\16.jar --output C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\desugar\debug\18.jar --input C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\0.jar --output C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\desugar\debug\2.jar --input C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\22.jar --output C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\desugar\debug\24.jar --input C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\1.jar --output C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\desugar\debug\3.jar --input C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\12.jar --output C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\desugar\debug\14.jar --input C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\3.jar --output C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\desugar\debug\5.jar --classpath_entry C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\CordovaLib\build\intermediates\intermediate-jars\debug\classes.jar --classpath_entry C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\classes\debug --classpath_entry C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\0.jar --classpath_entry C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\1.jar --classpath_entry C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\2.jar --classpath_entry C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\3.jar --classpath_entry C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\4.jar --classpath_entry C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\5.jar --classpath_entry C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\6.jar --classpath_entry C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\7.jar --classpath_entry C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\8.jar --classpath_entry C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\9.jar --classpath_entry C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\10.jar --classpath_entry C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\11.jar --classpath_entry C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\12.jar --classpath_entry C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\13.jar --classpath_entry C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\14.jar --classpath_entry C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\15.jar --classpath_entry C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\16.jar --classpath_entry C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\17.jar --classpath_entry C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\18.jar --classpath_entry C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\19.jar --classpath_entry C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\20.jar --classpath_entry C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\21.jar --classpath_entry C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\22.jar --classpath_entry C:\strony\www\polskieszlaki_new\aplikacja\platforms\android\app\build\intermediates\transforms\stackFramesFixer\debug\23.jar --bootclasspath_entry c:\Users\Lukasz\AppData\Local\Android\android-sdk\platforms\android-26\android.jar --bootclasspath_entry c:\Users\Lukasz\AppData\Local\Android\android-sdk\platforms\android-26\optional\org.apache.http.legacy.jar --bootclasspath_entry C:\Program Files\Java\jdk1.8.0_40\jre\lib\resources.jar --bootclasspath_entry C:\Program Files\Java\jdk1.8.0_40\jre\lib\rt.jar --bootclasspath_entry C:\Program Files\Java\jdk1.8.0_40\jre\lib\jsse.jar --bootclasspath_entry C:\Program Files\Java\jdk1.8.0_40\jre\lib\jce.jar --bootclasspath_entry C:\Program Files\Java\jdk1.8.0_40\jre\lib\charsets.jar --bootclasspath_entry C:\Program Files\Java\jdk1.8.0_40\jre\lib\jfr.jar --min_sdk_version 19 --nodesugar_try_with_resources_if_needed --desugar_try_with_resources_omit_runtime_classes}

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 43s
(node:23060) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

[OK] Your app has been deployed.
     Did you know you can live-reload changes from your app with --livereload?


Process finished with exit code 0
```

**Comment by htsnet** [comment]
I have a similar issue using Android Studio to build my Cordova project. When I install this plugin, I receive this error message in Android: Process 'command 'C:\Program Files\Android\Android Studio\jre\bin\java.exe'' finished with non-zero exit value 1

If I remove this plugin, the build is OK.

I tried with 2 apps and the issue is the same.

**Comment by flatherskevin** [comment]
I can confirm this issue. Tried cleaning, adding removing platforms, and reinstalling all packages and plugins with no luck.

**Comment by spyr0s** [comment]
Same issue here with cordova-android@7.1.0

**Comment by ivanov84** [comment]
I use cordova-android@7.1.0 and works well.
Add following:
configurations.all {
    resolutionStrategy {
        force 'com.android.support:support-v4:27.1.1'
    }
}

to gradle

**Comment by htsnet** [comment]
@ivanov84 > thanks for the tip and information. Could you tell me in what file this config must be inserted? Thanks.

**Comment by arkoak** [comment]
@ivanov84 , I tried adding the config to both platform/build.gradle and platform/app/build.gradle file in the end , however it did not succeed. Removing the plugin resolves the problem. 
Tried the same on 2 apps on Android 7.0.0

**Comment by ivanov84** [comment]
@htsnet @arkoak I used hook with replacing build-extras.gradle file with following code:
```
configurations.all {
    resolutionStrategy {
        force 'com.android.support:support-v4:27.1.1'
    }
}
```
hook code:
```
var fs = require('fs');
var android_dir = `platforms/android`;
var gradle_filename = 'build-extras.gradle';
var gradle_file = `scripts/${gradle_filename}`;
if (fs.existsSync(android_dir) && fs.existsSync(gradle_file)) {
  fs.createReadStream(gradle_file)
    .pipe(fs.createWriteStream(`${android_dir}/${gradle_filename}`));
}
```

hook in config:
`<hook src="scripts/copy_build_extras.js" type="before_build" />`

**Comment by s3ppo** [comment]
+1 doesnt work with ionic 3

**Comment by htsnet** [comment]
I changed the Gradle Scripts, build.gradle and included/changed all these lines inside dependencies:

    compile "com.google.android.gms:play-services-analytics:+"
    compile "com.android.support:support-v4:24.1.1+"
    compile "com.google.android.gms:play-services-base:+"
    compile "com.google.android.gms:play-services-ads:+"
    compile "com.google.gms:google-services:+"
    compile "com.google.android.gms:play-services-tagmanager:+"
    compile "com.android.support:customtabs:23.2.0"

I copied from another app that is working. After that, I could build and it´s running. I am testing just now to confirm that everything is OK.

Don´t ask me why....

**Comment by sonugpc** [comment]
I tried all the Solutions from here but the issue still there, App get Crashed on admob.banner.Prepare Method any expert solution?

**Comment by Riyaz0001** [comment]
thanks @htsnet

**Comment by arkoak** [comment]
investigated it again, a foolproof solution that seems to work every time and with other conflicting libraries is to set all occurances of com.google.** libraries to use version "+".
this can b achieved by doing a search replace in android and plugin folders of app

**Comment by mihawk007** [comment]
@spyr0s like me nothing works for me but i kept trying i just fix it right now 
first downgrade from cordova-android@7.1.0 to cordova-android@6.3.0
and then go to  \platforms\android\project.properties, replace PLAY_SERVICES_VERSION by “+” only like this : 

before : 
`com.google.android.gms:play-services-base:$PLAY_SERVICES_VERSION
com.google.android.gms:play-services-ads:$PLAY_SERVICES_VERSION `

after :
`com.google.android.gms:play-services-base:+
com.google.android.gms:play-services-ads:+`

thats works for me i hope he does for you too and every one else

Another way: install cordova plugin to create version automatically

`cordova plugin add cordova-android-play-services-gradle-release`

**Comment by tva3777** [comment]
just removed platform android and added again
`ionic cordova platform rm android`
`ionic cordova platform add android`

**Comment by PalakjainJain** [comment]
hey,
I tried all the solutions.but nothing works for me.
plz help me :-(

**Comment by pilz97** [comment]
hi,

i have the same problem, the above solutiosn didn't work for me.
Could anyone solve the error with other steps?

**Comment by mattiaa95** [comment]
Need to put this somewhere because it's what worked for me 
@mihawk007 thank you.

I enter in **platrfoms/android/project.properties** and change this:

cordova.system.library.2=com.google.android.gms:play-services-base:+
cordova.system.library.3=com.google.android.gms:play-services-ads:+

remove the versions and put + and work properly.
