### ISSUE TITLE
App crash after installing plugin

### ISSUE THREAD

**Issue by spiffytech** [ratson/cordova-plugin-admob-free#230]
I installed the plugin using `phonegap plugin add cordova-plugin-admob-free` and didn't make any other changes to my project.

When running the app, I now get this crash:

```
06-07 11:04:00.870  1732  1753 W WindowManager: Failed looking up window
06-07 11:04:00.870  1732  1753 W WindowManager: java.lang.IllegalArgumentException: Requested window android.view.ViewRootImpl$W@2095d01 does not exist
06-07 11:04:00.870  1732  1753 W WindowManager:         at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9422)
06-07 11:04:00.870  1732  1753 W WindowManager:         at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9413)
06-07 11:04:00.870  1732  1753 W WindowManager:         at com.android.server.wm.WindowManagerService.removeWindow(WindowManagerService.java:2393)
06-07 11:04:00.870  1732  1753 W WindowManager:         at com.android.server.wm.Session.remove(Session.java:202)
06-07 11:04:00.870  1732  1753 W WindowManager:         at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:3290)
06-07 11:04:00.870  1732  1753 W WindowManager:         at android.view.ViewRootImpl.doDie(ViewRootImpl.java:5917)
06-07 11:04:00.870  1732  1753 W WindowManager:         at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3626)
06-07 11:04:00.870  1732  1753 W WindowManager:         at android.os.Handler.dispatchMessage(Handler.java:102)
06-07 11:04:00.870  1732  1753 W WindowManager:         at android.os.Looper.loop(Looper.java:154)
06-07 11:04:00.870  1732  1753 W WindowManager:         at android.os.HandlerThread.run(HandlerThread.java:61)
06-07 11:04:00.870  1732  1753 W WindowManager:         at com.android.server.ServiceThread.run(ServiceThread.java:46)
```

**Comment by spiffytech** [comment]
I'm on the latest Cordova (8.0.0). Ensuring that I target Android API v27, I get this error:

```
06-11 19:12:16.227 19950 19950 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/internal/zzur;
06-11 19:12:16.227 19950 19950 E AndroidRuntime:        at com.google.android.gms.ads.BaseAdView.<init>(Unknown Source)
06-11 19:12:16.227 19950 19950 E AndroidRuntime:        at com.google.android.gms.ads.AdView.<init>(Unknown Source)
06-11 19:12:16.227 19950 19950 E AndroidRuntime:        at name.ratson.cordova.admob.banner.BannerExecutor$1.run(BannerExecutor.java:70)                                          
06-11 19:12:16.227 19950 19950 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:751)                                                                                                                  
06-11 19:12:16.227 19950 19950 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)           
06-11 19:12:16.227 19950 19950 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)                                                               
06-11 19:12:16.227 19950 19950 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6244)            
06-11 19:12:16.227 19950 19950 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)                                                               
06-11 19:12:16.227 19950 19950 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:887) 
06-11 19:12:16.227 19950 19950 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:777)                                                                                                       
06-11 19:12:16.227 19950 19950 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: com.google.android.gms.internal.zzur                                                                               
06-11 19:12:16.227 19950 19950 E AndroidRuntime:        at java.lang.VMClassLoader.findLoadedClass(Native Method)                                                                
06-11 19:12:16.227 19950 19950 E AndroidRuntime:        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)                                                                                                          
06-11 19:12:16.227 19950 19950 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
06-11 19:12:16.227 19950 19950 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)                                                                                                                
06-11 19:12:16.227 19950 19950 E AndroidRuntime:        ... 10 more                                          
06-11 19:12:16.227 19950 19950 E AndroidRuntime: Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/internal/zzee;
```
