### ISSUE TITLE
Error: EACCES: permission denied

### ISSUE THREAD

**Issue by arcadesindo** [ratson/cordova-plugin-admob-free#293]
**Got this problem in Phonegap CLI 8.0.0**

Error: EACCES: permission denied, open '/.cordova/lib/npm_cache/cordova-admob-sdk/0.20.0/package/src/ios/GoogleMobileAds.framework/Headers/DFPBannerView.h'
    at /usr/local/lib/npm/lib/node_modules/pgb-plugman-151/node_modules/pgb-cordova-lib/src/plugman/fetch.js:215:37
    at _rejected (/usr/local/lib/npm/lib/node_modules/pgb-plugman-151/node_modules/q/q.js:797:24)
    at /usr/local/lib/npm/lib/node_modules/pgb-plugman-151/node_modules/q/q.js:823:30
    at Promise.when (/usr/local/lib/npm/lib/node_modules/pgb-plugman-151/node_modules/q/q.js:1035:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/npm/lib/node_modules/pgb-plugman-151/node_modules/q/q.js:741:41)
    at /usr/local/lib/npm/lib/node_modules/pgb-plugman-151/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/npm/lib/node_modules/pgb-plugman-151/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Failed to fetch plugin cordova-admob-sdk@~0.20.0 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: EACCES: permission denied, open '/.cordova/lib/npm_cache/cordova-admob-sdk/0.20.0/package/src/ios/GoogleMobileAds.framework/Headers/DFPBannerView.h'

**Comment by emretascii** [comment]
try it 

chmod 777 /.cordova/lib/npm_cache/cordova-admob-sdk/0.20.0/package/src/ios/GoogleMobileAds.framework/Headers
