### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by infuzz** [ratson/cordova-plugin-admob-free#296]
Hi,
cordova 8.0.0
cordova-android 7.1.1
cordova-ios 4.5.5
after installing the plugin 
local build & phonegap build fail with long statck trace ;

........
:app:transformClassesWithStackFramesFixerForDebug UP-TO-DATE
:app:transformClassesWithDesugarForDebugException in thread "main" java.lang.IllegalArgumentException
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:108)
        at com.google.devtools.build.android.desugar.DefaultMethodClassFixer$DefaultMethodFinder.visit(DefaultMethodClassFixer.java:471)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at com.google.devtools.build.android.desugar.DefaultMethodClassFixer.defaultMethodsDefined(DefaultMethodClassFixer.java:319)
        at com.google.devtools.build.android.desugar.DefaultMethodClassFixer.visitEnd(DefaultMethodClassFixer.java:88)
        at org.objectweb.asm.ClassVisitor.visitEnd(Unknown Source)
        at com.google.devtools.build.android.desugar.InterfaceDesugaring.visitEnd(InterfaceDesugaring.java:85)
        at org.objectweb.asm.ClassVisitor.visitEnd(Unknown Source)
        at com.google.devtools.build.android.desugar.LambdaDesugaring.visitEnd(LambdaDesugaring.java:150)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at com.google.devtools.build.android.desugar.Desugar.desugarClassesInInput(Desugar.java:401)
        at com.google.devtools.build.android.desugar.Desugar.desugarOneInput(Desugar.java:326)
        at com.google.devtools.build.android.desugar.Desugar.desugar(Desugar.java:280)
        at com.google.devtools.build.android.desugar.Desugar.main(Desugar.java:584)

 FAILED
35 actionable tasks: 1 executed, 34 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDesugarForDebug'.
> com.android.build.api.transform.TransformException: j
.........................

Before installing build it didn't fail.
With the same base, I got multidex build  issue with  cordova-plugin-admob-PLUS

Is it possible to build with these with this cordova version ?
Thx

**Comment by realivanjx** [comment]
Try to re adding platforms (ex: run `cordova platform rm android` then `cordova platform add android`)

**Comment by infuzz** [comment]
Thx for answer, but I did it, also with cordova clean, without any success. Note that I got the same kind of error when trying to compli on phongap cli-8.0.0, android 7.1.1

**Comment by infuzz** [comment]
hi, with the new vesion 0.21 released two days ago, I can compile now on cli 8.0.0 and android 7.1.1 on my personnal cordova insatllation. But when trying to build on phonegap, I got an new issue with the dependent plugin "cordova-admob-sdk". Below the phonegab buil fail log:

.../...
plugman-151 install --platform android --project  --plugin cordova-plugin-admob-free@0.21.0 --nohooks=. --var ADMOB_APP_ID=ca-app-pub-xxxxxxxxxxxxxxxxxxx": Fetching plugin "cordova-plugin-admob-free@0.21.0" via npm
Installing "cordova-plugin-admob-free" at "0.21.0" for android
Fetching plugin "cordova-promise-polyfill@~0.0.2" via npm
Installing "cordova-promise-polyfill" at "0.0.2" for android
Android Studio project detected
Fetching plugin "cordova-admob-sdk@~0.20.0" via npm
Error during untar for /.cordova/lib/npm_cache/cordova-admob-sdk/0.20.0/package.tgz: Error: EACCES: permission denied, open '/.cordova/lib/npm_cache/cordova-admob-sdk/0.20.0/package/src/ios/GoogleMobileAds.framework/Headers/DFPBannerView.h'
Failed to install 'cordova-plugin-admob-free': CordovaError: Failed to fetch plugin cordova-admob-sdk@~0.20.0 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: EACCES: permission denied, open '/.cordova/lib/npm_cache/cordova-admob-sdk/0.20.0/package/src/ios/GoogleMobileAds.framework/Headers/DFPBannerView.h'
    at /usr/local/lib/npm/lib/node_modules/pgb-plugman-151/node_modules/pgb-cordova-lib/src/plugman/fetch.js:215:37
    at _rejected (/usr/local/lib/npm/lib/node_modules/pgb-plugman-151/node_modules/q/q.js:797:24)
    at /usr/local/lib/npm/lib/node_modules/pgb-plugman-151/node_modules/q/q.js:823:30
    at Promise.when (/usr/local/lib/npm/lib/node_modules/pgb-plugman-151/node_modules/q/q.js:1035:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/npm/lib/node_modules/pgb-plugman-151/node_modules/q/q.js:741:41)
    at /usr/local/lib/npm/lib/node_modules/pgb-plugman-151/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/npm/lib/node_modules/pgb-plugman-151/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Failed to fetch plugin cordova-admob-sdk@~0.20.0 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: EACCES: permission denied, open '/.cordova/lib/npm_cache/cordova-admob-sdk/0.20.0/package/src/ios/GoogleMobileAds.framework/Headers/DFPBannerView.h'



Any idea or suggestions ? Thx for your help.

**Comment by infuzz** [comment]
this is the same issue as in #293

**Comment by lfreneda** [comment]
Same issue here.. @infuzz Did you solve it?

**Comment by infuzz** [comment]
HI, some news?

**Comment by infuzz** [comment]
never solved.
