### ISSUE TITLE
Failed to install 'cordova-plugin-admob-free': Error: Variable(s) missing: ADMOB_APP_ID

### ISSUE THREAD

**Issue by JeetuChoudhary** [ratson/cordova-plugin-admob-free#298]
I am trying to install the plugin in Ionic V4 project by following the v4 documentation and I am not able to install it. It is throwing following Error:

```
Failed to install 'cordova-plugin-admob-free': Error: Variable(s) missing: ADMOB_APP_ID
    at Object.mergeVariables (C:\nvm\v8.10.0\node_modules\cordova\node_modules\cordova-lib\src\plugman\variable-merge.js:58:15)
    at C:\nvm\v8.10.0\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:315:44
    at _fulfilled (C:\nvm\v8.10.0\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\nvm\v8.10.0\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\nvm\v8.10.0\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:749:13)
    at C:\nvm\v8.10.0\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:557:44
    at flush (C:\nvm\v8.10.0\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
(node:7544) UnhandledPromiseRejectionWarning: Error: Variable(s) missing: ADMOB_APP_ID
    at Object.mergeVariables (C:\nvm\v8.10.0\node_modules\cordova\node_modules\cordova-lib\src\plugman\variable-merge.js:58:15)
    at C:\nvm\v8.10.0\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:315:44
    at _fulfilled (C:\nvm\v8.10.0\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\nvm\v8.10.0\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\nvm\v8.10.0\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:749:13)
    at C:\nvm\v8.10.0\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:557:44
    at flush (C:\nvm\v8.10.0\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:7544) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7544) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by jockamasagui** [comment]
Since the version 17 of play-services-ads and the 0.21.0 version of the plugin the ADMOB_APP_ID must be added to the AndroidManifest.xml. To install the plugin without errors and to insert the ADMOB_APP_ID to the manifest file automatically use the following code:

cordova plugin add cordova-plugin-admob-free --save --variable ADMOB_APP_ID="<YOUR_ADMOB_APP_ID_AS_FOUND_IN_ADMOB>"

**Comment by alcarazolabs** [comment]
Hey jockamasagui, thanks so much man!!
I had the same error of JeetuChoudhary..
Finally it works, now I have: admob-free; 0.22.0

`  <plugin name="cordova-plugin-admob-free" spec="0.22.0">`
```
λ cordova -v
8.1.1 (cordova-lib@8.1.0)

```
Ionic v.3
