### ISSUE TITLE
Adobe PhoneGap Build Help Need (Build Error)

### ISSUE THREAD

**Issue by ghost** [ratson/cordova-plugin-admob-free#306]
Hi i am using adobe phonegap for build android application, it do not support over 50mb size html5 app source code in there build.phonegap.com site. this is why i need to ad cordova-plugin-admob-free plugin with <plugin name="cordova-plugin-admob-free" /> line code in config.xml file in this case adobe auto download plugin sources + admob sdk in adobe server , but i am also not able to add ADMOB_APP_ID in config.xml file because i dont know how to add it in config file. this is why adobe dont build my app and show this error log, please help me how can i fix it.

Build Date: 2018-10-16 01:04:01 +0000
--------------------------------------------------------------------------------
PLUGIN OUTPUT
--------------------------------------------------------------------------------
"plugman-151 install --platform android --project /project --plugin cordova-plugin-admob-free --nohooks=.": Fetching plugin "cordova-plugin-admob-free" via npm
Installing "cordova-plugin-admob-free" at "0.21.0" for android
Failed to install 'cordova-plugin-admob-free': Error: Variable(s) missing: ADMOB_APP_ID
    at Object.mergeVariables (/usr/local/lib/npm/lib/node_modules/pgb-plugman-151/node_modules/pgb-cordova-lib/src/plugman/variable-merge.js:58:15)
    at /usr/local/lib/npm/lib/node_modules/pgb-plugman-151/node_modules/pgb-cordova-lib/src/plugman/install.js:315:44
    at _fulfilled (/usr/local/lib/npm/lib/node_modules/pgb-plugman-151/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/npm/lib/node_modules/pgb-plugman-151/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/npm/lib/node_modules/pgb-plugman-151/node_modules/q/q.js:749:13)
    at /usr/local/lib/npm/lib/node_modules/pgb-plugman-151/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/npm/lib/node_modules/pgb-plugman-151/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Variable(s) missing: ADMOB_APP_ID

**Comment by Phiphel** [comment]
Same issue here.

**Comment by Phiphel** [comment]
Adding app id to the config.xml seems to work

```
 	<plugin name="cordova-plugin-admob-free" spec="0.23.0"  source="npm" >
 		<variable name="ADMOB_APP_ID" value="YOURID" />
 	</plugin>
```
