### ISSUE TITLE
ionic 4 plugin_not_installed

### ISSUE THREAD

**Issue by abdosaeedelhassan** [ratson/cordova-plugin-admob-free#379]
hi,
firstly i do all steps
1- creating new project
ionic start admob blank
2- installing admob plugin
ionic cordova plugin add cordova-plugin-admob-free --save --variable ADMOB_APP_ID="ca-app-pub-xxxxxxxxxxxxxxxx~xxxxxxxxxx"
3- installing npm admob package
npm install @ionic-native/admob-free
4- importing AdMobFree in app.module.ts
5- in home page tring with next code
  showBanner() {

    let bannerConfig: AdMobFreeBannerConfig = {
        isTesting: true, // Remove in production
        autoShow: true
        //id: Your Ad Unit ID goes here
    };

    this.admob.banner.config(bannerConfig);

    this.admob.banner.prepare().then(() => {
        // success
    }).catch(e => console.log(e));

}

but when i am trying to run i receive that
[ng] [console.warn]: "Install the AdMobFree plugin: 'ionic cordova plugin add cordova-plugin-admob-free'"
[ng] [console.log]: "plugin_not_installed"

i don't now what the problem, please help

**Comment by kapik** [comment]
Hi! 
Same with `rewardVideo` :(

**Comment by abdosaeedelhassan** [comment]
also i am added

<plugin name="cordova-plugin-admob-free" spec="^0.27.0">
        <variable name="ADMOB_APP_ID" value="a-app-pub-xxxxxxxxxxxxxxxx~xxxxxxxxxx" />
    </plugin>

in config.xml, it worked now

**Comment by kapik** [comment]
Hey @abdosaeedelhassan  !
Thx for your help but I have a lot of errors with this changes 😕 

![2019-09-22_15-53-47](https://user-images.githubusercontent.com/511247/65388979-41f25200-dd51-11e9-9138-1a3946c433c3.png)

**Comment by abdosaeedelhassan** [comment]
your erros description not clear for me, i think you need to update your android sdk

**Comment by kapik** [comment]
I have already cleaned several times everything that could be cleaned in the project but I can't get this plugin to work.
My installation is recent so I have all the latest versions (Ionic, Android, Cordova...).
This plugin drives me crazy

**Comment by abdosaeedelhassan** [comment]
try this example
https://github.com/abdosaeedelhassan/admofree-rewardvideo

i hope that help you

**Comment by kapik** [comment]
I installed it on two phones (emulator):
- Pixel 2 API 29 (Android 10): the project is not being built
- Pixel API 28 (Android 9): the application starts but as soon as I switch to the second tab I have an error and the application closes:

```
    --------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.ionic.starter, PID: 3229
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/internal/zzur;
        at com.google.android.gms.internal.zzlf.zzdD(Unknown Source:0)
        at com.google.android.gms.ads.MobileAds.getRewardedVideoAdInstance(Unknown Source:0)
        at name.ratson.cordova.admob.rewardvideo.RewardVideoExecutor$1.run(RewardVideoExecutor.java:47)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: com.google.android.gms.internal.zzur
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.google.android.gms.internal.zzlf.zzdD(Unknown Source:0) 
        at com.google.android.gms.ads.MobileAds.getRewardedVideoAdInstance(Unknown Source:0) 
        at name.ratson.cordova.admob.rewardvideo.RewardVideoExecutor$1.run(RewardVideoExecutor.java:47) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/internal/zzee;
        at com.google.android.gms.internal.zzlf.zzdD(Unknown Source:0) 
        at com.google.android.gms.ads.MobileAds.getRewardedVideoAdInstance(Unknown Source:0) 
        at name.ratson.cordova.admob.rewardvideo.RewardVideoExecutor$1.run(RewardVideoExecutor.java:47) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.internal.zzee" on path: DexPathList[[zip file "/data/app/io.ionic.starter-FcuMA62rHfSpdFyvKkduLQ==/base.apk"],nativeLibraryDirectories=[/data/app/io.ionic.starter-FcuMA62rHfSpdFyvKkduLQ==/lib/x86, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)

```

Which version of android/API do you use?

**Comment by kapik** [comment]
😱 Seems to work with command `cordova` instead of `capacitor`
