### ISSUE TITLE
AdMobFree crahsed with google maps and firebase, ionic cordova

### ISSUE THREAD

**Issue by inigoMaxi** [ratson/cordova-plugin-admob-free#462]
LOGCAT:
2020-11-30 22:51:54.470 13428-13428/io.ionic.starter E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.ionic.starter, PID: 13428
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/internal/zzur;
        at com.google.android.gms.ads.BaseAdView.<init>(Unknown Source:3)
        at com.google.android.gms.ads.AdView.<init>(Unknown Source:1)
        at name.ratson.cordova.admob.banner.BannerExecutor$1.run(BannerExecutor.java:70)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.ClassNotFoundException: com.google.android.gms.internal.zzur
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.google.android.gms.ads.BaseAdView.<init>(Unknown Source:3) 
        at com.google.android.gms.ads.AdView.<init>(Unknown Source:1) 
        at name.ratson.cordova.admob.banner.BannerExecutor$1.run(BannerExecutor.java:70) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/internal/zzee;
        at com.google.android.gms.ads.BaseAdView.<init>(Unknown Source:3) 
        at com.google.android.gms.ads.AdView.<init>(Unknown Source:1) 
        at name.ratson.cordova.admob.banner.BannerExecutor$1.run(BannerExecutor.java:70) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.internal.zzee" on path: DexPathList[[zip file "/data/app/io.ionic.starter-wcoTUHXv5Yq1mLMNS9gBxA==/base.apk"],nativeLibraryDirectories=[/data/app/io.ionic.starter-wcoTUHXv5Yq1mLMNS9gBxA==/lib/x86, /data/app/io.ionic.starter-wcoTUHXv5Yq1mLMNS9gBxA==/base.apk!/lib/x86, /system/lib, /system/product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.google.android.gms.ads.BaseAdView.<init>(Unknown Source:3) 
        at com.google.android.gms.ads.AdView.<init>(Unknown Source:1) 
        at name.ratson.cordova.admob.banner.BannerExecutor$1.run(BannerExecutor.java:70) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by inigoMaxi** [comment]
https://github.com/ratson/cordova-plugin-admob-free/issues/229#issuecomment-586524520 solution!!!
