### ISSUE TITLE
Can not install

### ISSUE THREAD

**Issue by fmbuthia** [ratson/cordova-plugin-admob-free#51]
I could not install plugin on the latest cordova builds.

**Comment by vintage** [comment]
@fmbuthia I didn't have any problems installing it. Could you provide more details/logs as it's impossible to help you using data you have provided here.

**Comment by fmbuthia** [comment]
I tried to install using github url like - cordova plugin add https://github.com/ratson/cordova-plugin-admob-free. I was still able to install the other way though - cordova plugin add cordova-plugin-admob-free. So this is not a big deal thanks for the plugin.

**Comment by vintage** [comment]
I wasn't able to install the plugin using github url also, it have to do something with missing `www/admob.js` file. I don't really know why was it removed from the repo. @ratson?

`cordova plugin add https://github.com/ratson/cordova-plugin-admob-free.git`

Sample output:

```
Failed to install 'cordova-plugin-admob-free':Error: Uh oh!
ENOENT: no such file or directory, open '/Users/kamilrykowski/workspace/party_game/plugins/cordova-plugin-admob-free/www/admob.js'
    at Object.fs.openSync (fs.js:558:18)
    at Object.fs.readFileSync (fs.js:468:33)
    at install (/Users/kamilrykowski/workspace/party_game/platforms/android/cordova/lib/pluginHandlers.js:173:36)
    at ActionStack.process (/Users/kamilrykowski/workspace/party_game/platforms/android/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/Users/kamilrykowski/workspace/party_game/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:117:20)
    at PluginManager.addPlugin (/Users/kamilrykowski/workspace/party_game/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:147:17)
    at /Users/kamilrykowski/workspace/party_game/platforms/android/cordova/Api.js:254:18
    at _fulfilled (/Users/kamilrykowski/workspace/party_game/platforms/android/cordova/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/kamilrykowski/workspace/party_game/platforms/android/cordova/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/kamilrykowski/workspace/party_game/platforms/android/cordova/node_modules/q/q.js:796:13)


Error: Uh oh!
ENOENT: no such file or directory, open '/Users/kamilrykowski/workspace/party_game/plugins/cordova-plugin-admob-free/www/admob.js'
```

**Comment by ratson** [comment]
It won't work as `www/` is generated from `src/js/` via `babel`.
