### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by media0101** [ratson/cordova-plugin-admob-free#78]
When app run, showing in logcat monitor:

Ads: Invoke Firebase method getInstance error.
                                                        java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.measurement.AppMeasurement" on path: DexPathList[[zip file "/data/app/com.dbscalcio.app-1/base.apk"],nativeLibraryDirectories=[/data/app/com.dbscalcio.app-1/lib/arm, /vendor/lib, /system/lib]]
                                                            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                            at com.google.android.gms.ads.internal.scionintegration.b.a(:com.google.android.gms.DynamiteModulesA:166)
                                                            at com.google.android.gms.ads.internal.scionintegration.b.a(:com.google.android.gms.DynamiteModulesA:151)
                                                            at com.google.android.gms.ads.internal.scionintegration.b.f(:com.google.android.gms.DynamiteModulesA:42)
                                                            at com.google.android.gms.ads.internal.request.c.a(:com.google.android.gms.DynamiteModulesA:26)
                                                            at com.google.android.gms.ads.internal.util.b.run(:com.google.android.gms.DynamiteModulesA:4)
                                                            at com.google.android.gms.ads.internal.util.af.call(:com.google.android.gms.DynamiteModulesA:3)
                                                            at com.google.android.gms.ads.internal.util.ag.run(:com.google.android.gms.DynamiteModulesA:3)
                                                            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                            at java.lang.Thread.run(Thread.java:818)
                                                        	Suppressed: java.lang.ClassNotFoundException: com.google.android.gms.measurement.AppMeasurement
                                                            at java.lang.Class.classForName(Native Method)
                                                            at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                            at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                            		... 13 more
                                                         Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
06-15 18:27:37.015 29356-32589/com.dbscalcio.app W/Ads: The Google Mobile Ads SDK will not integrate with Firebase. Admob/Firbase integration requires the latest Firebase SDK jar, but Firebase SDK is either missing or out of date

It's normal this error?
Anyhow, admob banner test is visible (in debug mode).

**Comment by ElieSauveterre** [comment]
I have the same error. 
It seems to only crash on the first time I call admob.banner.prepare and the promise is resolved without error and return "OK"
